### ISSUE TITLE
Name of the department

### ISSUE THREAD

**Issue by yuttai** [liang-chen/PhDThesisTemplate#1]
The current department name in the title page is

> Department of Informatics, Computing and Engineering

However, [it should be either one of the following](https://www.sice.indiana.edu/about/departments/index.html).

> School of Informatics, Computing, and Engineering
> Department of Computer Science
> Department of Informatics

If you haven't submitted your thesis, you may want to update this...

Besides, I am modifying [the iuphd document class from the Department of Mathematics](https://github.com/yuttai/iuphd), I think summarizing the thesis template into a document class is a better idea, and they have already had a good documentation... However, I might help updating yours to make it more user friendly as well... Please tell me if you have any suggestion... Thanks : )

**Comment by yuttai** [comment]
Besides, README.md page doesn't specify which file is the main document...

**Comment by liang-chen** [comment]
Yu-Tsung, Thanks for the suggestions. I'll update the department name. Thanks for correcting me :)

I think both are okay as long as it can provide the template that meets the school's requirements. We can both keep improving the templates and let others choose their preferred one to use.

**Comment by yuttai** [comment]
Thanks. I might keep updating mine, but also check yours if I have any LaTeX questions... etc. , and create an issue if I find any : )
